using System.Collections;
using UnityEngine;
using DHJ.Core;
using DHJ.UI;

namespace DHJ.Demo
{
    /// <summary>
    /// SIH Presentation Mode (spec §74): a guided tour that captions the judge
    /// through the museum's key systems — character, six doors, archive,
    /// manuscript viewer, memorials, quiz, AI assistant, results. The player can
    /// take control at any moment; captions simply keep flowing.
    /// </summary>
    public class PresentationModeController : MonoBehaviour
    {
        private void Start()
        {
            if (!GameManager.I.PresentationMode) { enabled = false; return; }
            StartCoroutine(Tour());
        }

        private IEnumerator Tour()
        {
            var ui = UIManager.instance;
            yield return new WaitForSeconds(8f);

            Caption("PRESENTATION MODE — a guided look at the Digital Heritage platform.", 5f);
            yield return new WaitForSeconds(5.5f);

            Caption("You are Dr. B. R. Ambedkar. Character model, suit, glasses and tie are generated by the character pipeline.", 6f);
            yield return new WaitForSeconds(6.5f);

            Caption("Behind you: SIX gallery doors — Early Life, Social Reform, Law & Constitution, Manuscripts, Memorials, Legacy.", 6f);
            yield return new WaitForSeconds(6.5f);

            Caption("Walk up to any exhibit and press E (or INTERACT) to open it. Try the reception Archive Guide terminal first.", 6f);
            yield return new WaitForSeconds(6.5f);

            Caption("Every exhibit opens a panel with sources. Document exhibits have a page-through viewer.", 6f);
            yield return new WaitForSeconds(6.5f);

            Caption("Quizzes explain every answer. The Preamble Challenge is in Door 3 — Law & Constitution.", 6f);
            yield return new WaitForSeconds(6.5f);

            Caption("The Archive Guide (Door 6) answers questions from the approved archive and always cites sources.", 6f);
            yield return new WaitForSeconds(6.5f);

            Caption("Press TAB / ARCHIVE to open your Digital Archive and search everything instantly.", 6f);
            yield return new WaitForSeconds(6.5f);

            Caption("All six doors are unlocked in this demo. Your guided objective is shown top-left. Enjoy the visit.", 7f);
        }

        private static void Caption(string s, float seconds) =>
            UIManager.instance?.ShowSubtitle(s, seconds);
    }
}
